name: 同步容器镜像

# 触发条件：在 push 到 master 分支后
on:
  push:

# 任务
jobs:
  sync-images:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 准备同步工具
        run: bash ./tools.sh

      - name: 同步翼龙镜像
        run: image-syncer -r 3 --auth config.json --images images/pter.yml

      - name: 同步ELK镜像
        run: image-syncer -r 3 --auth config.json --images images/elk.yml
